[package]
name = "okx-api-example"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "^0.22.1"
chrono = "^0.4.24"
hmac = "^0.12.1"
reqwest = { version = "^0.12.8", features = ["json"] }
sha2 = "^0.10.8"
dotenv = "0.15.0"
tokio = { version = "1.36.0", features = ["full"] }
